"""
Resources package for PowerGuard OS Monitor.
"""
from .styles import (
    COLOR_BG,
    COLOR_SURFACE,
    COLOR_SURFACE_WARM,
    COLOR_SIDEBAR,
    COLOR_BORDER,
    COLOR_BORDER_LIGHT,
    COLOR_NAV_ACTIVE,
    COLOR_NAV_HOVER,
    COLOR_PRIMARY,
    COLOR_PRIMARY_HOVER,
    COLOR_PRIMARY_LIGHT,
    COLOR_SUCCESS,
    COLOR_SUCCESS_LIGHT,
    COLOR_WARNING,
    COLOR_WARNING_LIGHT,
    COLOR_DANGER,
    COLOR_DANGER_LIGHT,
    COLOR_TEXT_PRIMARY,
    COLOR_TEXT_SECONDARY,
    COLOR_TEXT_MUTED,
    MAIN_STYLESHEET
)
from .icons import get_icon, get_pixmap

__all__ = [
    "COLOR_BG",
    "COLOR_SURFACE",
    "COLOR_SURFACE_WARM",
    "COLOR_SIDEBAR",
    "COLOR_BORDER",
    "COLOR_BORDER_LIGHT",
    "COLOR_NAV_ACTIVE",
    "COLOR_NAV_HOVER",
    "COLOR_PRIMARY",
    "COLOR_PRIMARY_HOVER",
    "COLOR_PRIMARY_LIGHT",
    "COLOR_SUCCESS",
    "COLOR_SUCCESS_LIGHT",
    "COLOR_WARNING",
    "COLOR_WARNING_LIGHT",
    "COLOR_DANGER",
    "COLOR_DANGER_LIGHT",
    "COLOR_TEXT_PRIMARY",
    "COLOR_TEXT_SECONDARY",
    "COLOR_TEXT_MUTED",
    "MAIN_STYLESHEET",
    "get_icon",
    "get_pixmap"
]
